### ISSUE TITLE
404 error for Test_datasets

### ISSUE THREAD

**Issue by hamidqaedi** [mickaelleclercq/BioDiscML#1]
Hi,
There is no page at :

> https://github.com/mickaelleclercq/BioDiscML/tree/master/release/Test_datasets 

It returns 404 error. 
Should I check other any other place to find Test_datasets? More specifically I am looking for some reading materials that help me to use BioDiscML in my research. 
Please  provide some more detailed vignette or manual. 

Thank you in advanve,
Hamid

**Comment by mickaelleclercq** [comment]
Hi,
Sorry for that. I have re-uploaded the missing folder

--
Mickael
