### ISSUE TITLE
How did it calculate the BER or other metrics (ACC, AUC,et) for multiclass task?

### ISSUE THREAD

**Issue by shenwanxiang** [mickaelleclercq/BioDiscML#2]
Hi, I would like to know how BER calculated for the Stem cell dataset? This is not a binary classification task,

is the BER calculated by the average of each class's BER  or by the formule ((b+c)/(a+b+c)+(d+f)/(d+e+f)+(g+h)/(g+h+i))/3 for 3 classes such as Stem Cell data(MINT) ?

http://research.ics.aalto.fi/events/eyechallenge2005/evaluation.shtml

**Comment by mickaelleclercq** [comment]
In source code (src/utils/Weka_module.java, line 2316) you will find: 

BER (Balanced error rate) calculated based on https://arxiv.org/pdf/1207.3809.pdf

BER = Utils.doubleToString(0.5 * ((eval.weightedFalsePositiveRate()) + (eval.weightedFalseNegativeRate())), 12, 4).trim();
This is equivalent to 0.5 x ( FPR + FNR)
