### ISSUE TITLE
Any insight of error? java.lang.ArrayIndexOutOfBoundsException: 1

### ISSUE THREAD

**Issue by metajinomics** [mickaelleclercq/BioDiscML#3]
Hi I am getting the error near the end of the process

```
Bootstrap .632+ rule calculated on TRAIN set of trees.RandomForest -I 50 -K 0 -S 1 optimized by AUC...
0.462

# Average MCC: 0.165
# Average MAE: 0.444
java.lang.ArrayIndexOutOfBoundsException: 1
        utils.Weka_module$ClassificationResultsObject.getFeatureRankingResults(Weka_module.java:2556)
        biodiscml.BestModelSelectionAndReport.<init>(BestModelSelectionAndReport.java:775)
        biodiscml.Main.main(Main.java:173)

        at utils.Weka_module$ClassificationResultsObject.getFeatureRankingResults(Weka_module.java:2556)
        at biodiscml.BestModelSelectionAndReport.<init>(BestModelSelectionAndReport.java:775)
        at biodiscml.Main.main(Main.java:173)
Search correlated features (spearman)...[done]
Search correlated features (pearson)...[done]
Search similar ranking scores (infogain for classification or relieFf) in the original dataset...java.lang.ArrayIndexOutOfBoundsException: 1
        utils.Weka_module$ClassificationResultsObject.getFeatureRankingResults(Weka_module.java:2556)
        biodiscml.BestModelSelectionAndReport.<init>(BestModelSelectionAndReport.java:865)
        biodiscml.Main.main(Main.java:173)

        at utils.Weka_module$ClassificationResultsObject.getFeatureRankingResults(Weka_module.java:2556)
        at biodiscml.BestModelSelectionAndReport.<init>(BestModelSelectionAndReport.java:865)
        at biodiscml.Main.main(Main.java:173)
```

This is the config file that I used
```
project=myProject
trainFile=feature_table.csv
sampling=false
doClassification=true
classificationClassName=Label
numberOfBestModels=10
```

I don't see the above error when I used the example data in BioDiscML/release/Test_datasets/CNS. So perhaps specific to my input data? Do you have any insight into what would be the cause of the error?

BTW, I used Ubuntu 20.04, Java 8

**Comment by mickaelleclercq** [comment]
Looks like there was a problem in the file b containing information gain ranking results, or it cannot perform information gain ranking for various reasons. The average MCC you get is very low, so you have a very bad model here, I wouldn't trust this result

**Comment by metajinomics** [comment]
I found that the error `Cannot handle numeric class!` showed up before the above error. It was resolved after the change class value from 0/1 into TRUE/FALSE. 

Also, appreciate your insight of low average MCC. I agree that the result does not look has a good prediction.

**Comment by mickaelleclercq** [comment]
"Cannot handle numeric class!" can be a problem for some classifiers. 
Every features that should be categorial but are in numeric values must be modified. TRUE/FALSE instead of 1/0 is a good approach, but you can simply add a random character before your numeric value also (ex: _1 and _0)  to force BioDiscML to see it a string.
