### ISSUE TITLE
Install on MacOS 

### ISSUE THREAD

**Issue by fboellmann** [mickaelleclercq/BioDiscML#4]
Sorry for the stupid question - first time try on Mac,
I installed JAVA on MacBook Pro M1

java -version
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.331-b09, mixed mode)

I downloaded the jar file, but when I try to execute to see command line argument options I get this error message:

java -jar biodiscml.jar 
Error: Invalid or corrupt jarfile biodiscml.jar

Do I have to run it with full command line arguments and sample data to test it?
Thanks

Frank

**Comment by mickaelleclercq** [comment]
Hi, 
I have downloaded the last jar available in https://github.com/mickaelleclercq/BioDiscML/tree/master/release

I don't have a mac, so I can't really test that. But I have a windows and linux with different versions of java 1.8 and all are working well.

Maybe try to re-download it

On Windows:

```Bash
E:\Downloads>java -version
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

E:\Downloads>java -jar biodiscml.jar
#### BioDiscML ####

#### Parsing options...
[error] No mode selected (train, bestmodel or predict). Add -train or -bestmodel or -predict to your command line
```

On WSL (Windows Subsystem for Linux)
```Bash
(base) user:/mnt/e/Downloads$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)

(base) user:/mnt/e/Downloads$ java -jar biodiscml.jar
#### BioDiscML ####

#### Parsing options...
[error] No mode selected (train, bestmodel or predict). Add -train or -bestmodel or -predict to your command line
```

On linux
```Bash
-bash-4.2$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
-bash-4.2$ java -jar biodiscml.jar
#### BioDiscML ####

#### Parsing options...
[error] No mode selected (train, bestmodel or predict). Add -train or -bestmodel or -predict to your command line

```

**Comment by fboellmann** [comment]
Too bad, I downloaded per your instructions, but same outcome.
